// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250122014921_update_ViTri_LyDoNghi")]
    partial class update_ViTri_LyDoNghi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.BoPhan", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ten_bo_phan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("bo_phan");
                });

            modelBuilder.Entity("API.Models.LoaiPhep", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("so_ngay_nghi")
                        .HasColumnType("int");

                    b.Property<string>("ten_loai_phep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("loai_phep");
                });

            modelBuilder.Entity("API.Models.LyDoNghi", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("dien_giai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ky_hieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ly_do_nghi");
                });

            modelBuilder.Entity("API.Models.NghiPhep", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ban_giao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ky_hieu_ly_do")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("loai_phep_id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ly_do")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ngay_nghi")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ngay_xu_ly")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("nghi_den")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("nghi_tu")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("nv_id")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("nv_xu_ly")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("so_ngay_nghi")
                        .HasColumnType("int");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("nghi_phep");
                });

            modelBuilder.Entity("API.Models.NhanVien", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("bo_phan_id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("cong_viec")
                        .HasColumnType("longtext");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gioi_tinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ma_nv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ma_vi_tri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vi_tri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("nhan_vien");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("id_nv")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ma_nv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("API.Models.ViTri", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ma_vi_tri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ten_vi_tri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ten_vi_tri_en")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("vi_tri");
                });
#pragma warning restore 612, 618
        }
    }
}
