worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    server {
        listen 5025;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }
        gzip on;
        gzip_types text/plain text/css application/json application/javascript;
        gzip_vary on;
        gzip_min_length 1024;

        # Bật Cache-Control để tránh tải lại file JS không cần thiết
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
